#pragma once

/* snapast parameters; configurable in menuconfig */
#define CONFIG_SNAPCAST_SERVER_USE_MDNS 1
#define CONFIG_SNAPCAST_SERVER_HOST "192.168.8.102"
#define CONFIG_SNAPCAST_SERVER_PORT 1704
#define CONFIG_SNAPCAST_BUFF_LEN 4000
#define CONFIG_SNAPCAST_CLIENT_NAME "arduino-snapclient"
#define CONFIG_BITS_PER_SAMPLE 16
#define CONFIG_SNTP_SERVER "pool.ntp.org"
#define CONFIG_SNTP_TIMEZONE "UTC"

#define CONFIG_WEBSOCKET_SERVER_MAX_CLIENTS 20
#define CONFIG_WEBSOCKET_SERVER_QUEUE_SIZE 10
#define CONFIG_WEBSOCKET_SERVER_QUEUE_TIMEOUT 30
#define CONFIG_WEBSOCKET_SERVER_TASK_STACK_DEPTH 6000
#define CONFIG_WEBSOCKET_SERVER_TASK_PRIORITY 5

#define CONFIG_WIFI_SSID "piratnet"
#define CONFIG_WIFI_PASSWORD "12341234"

#define CONFIG_USE_PSRAM
#define CONFIG_SNAPCLIENT_SNTP_ENABLE
