#pragma once

/* snapast parameters; configurable in menuconfig */
#define CONFIG_SNAPCAST_SERVER_USE_MDNS 1
#define CONFIG_SNAPCAST_SERVER_HOST "192.168.1.38"
#define CONFIG_SNAPCAST_SERVER_PORT 1704
#define CONFIG_SNAPCAST_BUFF_LEN 4000
#define CONFIG_SNAPCAST_CLIENT_NAME "arduino-snapclient"
#define CONFIG_BITS_PER_SAMPLE 16
#define CONFIG_SNTP_SERVER "pool.ntp.org"
#define CONFIG_SNTP_TIMEZONE "UTC"

#define CONFIG_WEBSOCKET_SERVER_MAX_CLIENTS 10
#define CONFIG_WEBSOCKET_SERVER_QUEUE_SIZE 10
#define CONFIG_WEBSOCKET_SERVER_QUEUE_TIMEOUT 30
#define CONFIG_WEBSOCKET_SERVER_TASK_PRIORITY 5
#define CONFIG_WEBSOCKET_SERVER_TIMEOUT_SEC 10
#define CONFIG_WEBSOCKET_SERVER_TIMEOUT_USEC 0

// define stack for tasks
#define CONFIG_TASK_STACK_HTTP (5 * 1024)
#define CONFIG_TASK_STACK_DSP_I2S (4 * 1024)
#define CONFIG_TASK_STACK_WS_SERVER (5 * 1024)
#define CONFIG_TASK_STACK_SERVER (5 * 1024)
#define CONFIG_TASK_STACK_SERVER_HANDLE (5 * 1024)

// wifi
#define CONFIG_WIFI_SSID "piratnet"
#define CONFIG_WIFI_PASSWORD "12341234"

#define CONFIG_USE_PSRAM true
#define CONFIG_PSRAM_LIMIT 512
#define CONFIG_SNAPCLIENT_SNTP_ENABLE true
#define CONFIG_SNAPCLIENT_USE_MDNS true
